m = 1; 
k = 4; 
x0 = 1; 
v0 = 0; 
omega_n = sqrt(k/m);
t = linspace(0, 10, 1000); 
zeta_undamped = 0;
omega_d_undamped = omega_n * sqrt(1 - zeta_undamped^2);
x_undamped = x0 * cos(omega_n * t) + (v0 / omega_n) * sin(omega_n * t);
zeta_underdamped = 0.3;
omega_d_underdamped = omega_n * sqrt(1 - zeta_underdamped^2);
x_underdamped = exp(-zeta_underdamped * omega_n * t) .* ...
    (x0 * cos(omega_d_underdamped * t) + (v0 + zeta_underdamped * omega_n * x0) / omega_d_underdamped * sin(omega_d_underdamped * t));
zeta_overdamped = 1.2;
r1 = -zeta_overdamped * omega_n + omega_n * sqrt(zeta_overdamped^2 - 1);
r2 = -zeta_overdamped * omega_n - omega_n * sqrt(zeta_overdamped^2 - 1);
A = (v0 - r2 * x0) / (r1 - r2);
B = (r1 * x0 - v0) / (r1 - r2);
x_overdamped = A * exp(r1 * t) + B * exp(r2 * t);
figure;
subplot(3, 1, 1);
plot(t, x_undamped, '--k', 'LineWidth', 1.5, 'Marker', 'o', 'MarkerIndices', 1:100:length(t), 'MarkerSize', 4);
title('Undamped Case (\zeta = 0)', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement (m)', 'FontSize', 12);
grid on;
subplot(3, 1, 2);
plot(t, x_underdamped, '-.m', 'LineWidth', 1.5, 'Marker', 's', 'MarkerIndices', 1:80:length(t), 'MarkerSize', 4);
title('Underdamped Case (\zeta = 0.3)', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement (m)', 'FontSize', 12);
grid on;
subplot(3, 1, 3);
plot(t, x_overdamped, ':c', 'LineWidth', 1.5, 'Marker', '^', 'MarkerIndices', 1:150:length(t), 'MarkerSize', 5);
title('Overdamped Case (\zeta = 1.2)', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement (m)', 'FontSize', 12);
grid on;
set(gcf, 'Color', [0.95, 0.95, 0.95]); 
