m = 1;
k = 4; 
F0 = 6;
omega_n = sqrt(k/m);
t = linspace(0, 20, 1000);
zeta_undamped = 0; 
omega_d_undamped = omega_n; 
x_undamped = (F0/k) * (1 - cos(omega_d_undamped * t));
zeta_underdamped = 0.3;
omega_d_underdamped = omega_n * sqrt(1 - zeta_underdamped^2);
x_underdamped = (F0/k) * (1 - exp(-zeta_underdamped * omega_n * t) .* ...
(cos(omega_d_underdamped * t) + (zeta_underdamped * omega_n / omega_d_underdamped) * sin(omega_d_underdamped * t)));
zeta_overdamped = 1.2;
c = 2 * zeta_overdamped * sqrt(k * m);
r = roots([m, c, k]);
r1 = r(1); 
r2 = r(2); 
A = [1, 1; r1, r2]; 
B = [F0/k; 0]; 
sol = A \ B;
A1 = -sol(1);
A2 = -sol(2);
x_p = F0 / k;
x_overdamped = (A1 * exp(r1 * t)) + (A2 * exp(r2 * t)) + x_p;
figure;
subplot(3, 1, 1);
plot(t, x_undamped, '--k', 'LineWidth', 1.5, 'Marker', 'o', 'MarkerIndices', 1:100:length(t), 'MarkerSize', 4);
title('Undamped Case: \zeta = 0', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement(m)', 'FontSize', 12);
grid on;
subplot(3, 1, 2);
plot(t, x_underdamped, '-.m', 'LineWidth', 1.5, 'Marker', 's', 'MarkerIndices', 1:80:length(t), 'MarkerSize', 4);
title('Underdamped Case: \zeta = 0.3', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement(m)', 'FontSize', 12);
grid on;
subplot(3, 1, 3);
plot(t, x_overdamped, ':c', 'LineWidth', 1.5, 'Marker', '^', 'MarkerIndices', 1:150:length(t), 'MarkerSize', 5);
title('Overdamped Case: \zeta = 1.2', 'FontSize', 14, 'FontName', 'Arial');
xlabel('Time (s)', 'FontSize', 12);
ylabel('Displacement(m)', 'FontSize', 12);
grid on;
set(gcf, 'Color', [0.95, 0.95, 0.95]);
